// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BuySearch: typeof import('./src/components/buy/buySearch.vue')['default']
    ControlStockDialog: typeof import('./src/components/ControlStock/ControlStockDialog.vue')['default']
    CountTo: typeof import('./src/components/ui-lib/count-to/CountTo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Linechart: typeof import('./src/components/driver/rightchart/linechart.vue')['default']
    MapChina: typeof import('./src/components/driver/MapChina.vue')['default']
    NeedSearch: typeof import('./src/components/need/needSearch.vue')['default']
    Piechart: typeof import('./src/components/driver/leftchart/piechart.vue')['default']
    Rankchart: typeof import('./src/components/driver/leftchart/rankchart.vue')['default']
    RolePermission: typeof import('./src/components/role/role-permission.vue')['default']
    Totalchart: typeof import('./src/components/driver/rightchart/totalchart.vue')['default']
    ValidateCode: typeof import('./src/components/login/ValidateCode.vue')['default']
    VDialog: typeof import('./src/components/ui-lib/v-dialog/v-dialog.vue')['default']
    VDrawer: typeof import('./src/components/ui-lib/v-drawer/v-drawer.vue')['default']
    VNoneData: typeof import('./src/components/ui-lib/v-noneData/v-noneData.vue')['default']
    VSearchNac: typeof import('./src/components/ui-lib/v-searchNac/v-searchNac.vue')['default']
  }
}

export { }
